Repository 2025-1-CECD-HELP/GenD-client, pull requests merged in 2025-05, with the labels that each got.

#44 Feature/#43 - 공통 드롭다운 메뉴 컴포넌트 구현
  src/components/DropDownMenu/index.stories.tsx
  src/components/DropDownMenu/index.style.ts
  src/components/DropDownMenu/index.tsx
  src/components/DropDownMenu/index.type.ts
Labels: ✨ feature, :woman: 정선 :woman:

#53 Feature/#52 - iOS FCM(Firebase Cloud Message) Setting
  .gitignore
  App.tsx
  ios/GenD.xcodeproj/project.pbxproj
  ios/GenD/AppDelegate.swift
  ios/GenD/Info.plist
  ios/GenD/PrivacyInfo.xcprivacy
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/config/firebase.ts
  yarn.lock
Labels: 👨🏻 규진 👨🏻, ✨ feature

#57 Feature/#56 - 로그인 기능 구현, 디버깅 프로세스 로직, 환경 변수를 활용한 백엔드 API 요청
  App.tsx
  babel.config.js
  index.js
  ios/GenD.xcodeproj/project.pbxproj
  ios/GenD/AppDelegate.swift
  ios/GenD/GenD.entitlements
  ios/GenD/GenDDebug.entitlements
  ios/GenD/GenDRelease.entitlements
  ios/GenD/Info.plist
  ios/GenD/PrivacyInfo.xcprivacy
  ios/Podfile
  ios/Podfile.lock
  package.json
  src/contexts/auth/AuthContext.tsx
  src/screens/login/hooks/useFCM.ts
  src/screens/login/hooks/useOauthLoginMutation.ts
  src/screens/login/index.tsx
  src/services/api/axios.ts
  src/services/api/privateInterceptor.ts
  src/services/api/publicInterceptor.ts
  src/services/api/type.ts
  src/services/auth/letsgo
  src/services/auth/oAuthLogin.ts
  src/services/auth/types.ts
  src/types/env.d.ts
  src/utils/debug.ts
  yarn.lock
Labels: 👨🏻 규진 👨🏻, ✨ feature, 🐛 bug

#59 Feature/#58 - suspense 및 errorboundary를 통한 에러 및 로딩 프로세스 통일 + Jest 를 활용한 Testing
  App.tsx
  __tests__/App.test.tsx
  jest.config.js
  package.json
  src/components/FallBackUI/Error/AdaptiveErrorFallbackUI.stories.tsx
  src/components/FallBackUI/Error/AdaptiveErrorFallbackUI.tsx
  src/components/FallBackUI/Error/AxiosErrorFallbackUI.stories.tsx
  src/components/FallBackUI/Error/AxiosErrorFallbackUI.style.ts
  src/components/FallBackUI/Error/AxiosErrorFallbackUI.tsx
  src/components/FallBackUI/Error/ParsingErrorFallbackUI.stories.tsx
  src/components/FallBackUI/Error/ParsingErrorFallbackUI.style.ts
  src/components/FallBackUI/Error/ParsingErrorFallbackUI.tsx
  src/components/FallBackUI/Error/RenderingErrorFallbackUI.stories.tsx
  src/components/FallBackUI/Error/RenderingErrorFallbackUI.style.ts
  src/components/FallBackUI/Error/RenderingErrorFallbackUI.tsx
  src/components/FallBackUI/Error/types.ts
  src/components/FallBackUI/Loading/AdaptiveLoadingFallbackUI.stories.tsx
  src/components/FallBackUI/Loading/AdaptiveLoadingFallbackUI.style.ts
  src/components/FallBackUI/Loading/AdaptiveLoadingFallbackUI.tsx
  src/services/api/privateInterceptor.ts
  src/services/api/publicInterceptor.ts
  src/test/error.test.ts
  src/utils/error.ts
  yarn.lock
Labels: 👨🏻 규진 👨🏻, ✨ feature

#62 Feature/#60 - 회의록 선택, 회의 도중, 회의록 미리보기 프로세스 구현
  android/app/src/main/AndroidManifest.xml
  ios/GenD/Info.plist
  ios/Podfile.lock
  package.json
  src/assets/images/svg/header/light.svg
  src/assets/images/svg/meeting/index.ts
  src/assets/images/svg/meeting/mic.svg
  src/assets/images/svg/meeting/pause.svg
  src/assets/images/svg/meeting/resume.svg
  src/assets/images/svg/meeting/stop.svg
  src/components/CommonModal/index.style.ts
  src/components/CommonModal/index.tsx
  src/components/FallBackUI/Error/ParsingErrorFallbackUI.tsx
  src/components/Template/TemplateList.tsx
  src/components/Template/index.const.ts
  src/components/Template/index.style.ts
  src/components/Template/useTemplateList.ts
  src/navigation/navigator.tsx
  src/navigation/types.ts
  src/screens/meeting/index.style.ts
  src/screens/meeting/index.tsx
  src/screens/recording/components/Pursering/index.style.ts
  src/screens/recording/components/Pursering/index.tsx
  src/screens/recording/components/RecordingPreviewModal/index.style.ts
  src/screens/recording/components/RecordingPreviewModal/index.tsx
  src/screens/recording/components/RecordingSubmitModal/index.style.ts
  src/screens/recording/components/RecordingSubmitModal/index.tsx
  src/screens/recording/hooks/useRecord.ts
  src/screens/recording/hooks/useSubmitRecord.ts
  src/screens/recording/index.style.ts
  src/screens/recording/index.tsx
  src/screens/recording/utils/formatTime.ts
  src/services/api/axios.ts
  src/services/auth/index.ts
  src/services/meeting/index.ts
  src/services/meeting/types.ts
  src/types/env.d.ts
  src/types/theme.d.ts
  yarn.lock
Labels: 👨🏻 규진 👨🏻, ✨ feature, 🎨 refactor

#66 Feature/#65 - 워크스페이스 선택 화면 구현
  src/assets/images/png/workspace/enter_workspace.png
  src/assets/images/png/workspace/make_workspace.png
  src/assets/images/svg/common/gend_logo.svg
  src/assets/images/svg/common/index.ts
  src/components/CommonModal/index.tsx
  src/components/WorkspaceBottomSheet/index.style.ts
  src/components/WorkspaceBottomSheet/index.tsx
  src/constants/mutationKeys.ts
  src/constants/queryKeys.ts
  src/constants/routes.ts
  src/contexts/bottomSheet/BottomSheetContext.tsx
  src/contexts/workspace/WorkspaceContenxt.tsx
  src/navigation/navigator.tsx
  src/navigation/types.ts
  src/screens/create-workspace/components/InviteMemberModal/index.style.ts
  src/screens/create-workspace/components/InviteMemberModal/index.tsx
  src/screens/create-workspace/hooks/useCreateWorkspace.tsx
  src/screens/create-workspace/hooks/useCreateWorkspaceMutation.ts
  src/screens/create-workspace/index.style.ts
  src/screens/create-workspace/index.tsx
  src/screens/init-workspace/index.style.ts
  src/screens/init-workspace/index.tsx
  src/screens/post-detail/index.style.ts
  src/screens/post-detail/index.tsx
Labels: 👨🏻 규진 👨🏻, ✨ feature

#68 Feature/#67 - 워크스페이스 멤버 추가, 리스트, 멤버 설정 기능 구현
  src/constants/mutationKeys.ts
  src/screens/index.ts
  src/screens/member/components/AddMemberModal/index.style.ts
  src/screens/member/components/AddMemberModal/index.tsx
  src/screens/member/components/MemberSettingModal/index.style.ts
  src/screens/member/components/MemberSettingModal/index.tsx
  src/screens/member/constants/mockData.ts
  src/screens/member/hooks/useMemberListQuery.ts
  src/screens/member/hooks/useMemberMutation.ts
  src/screens/member/index.style.ts
  src/screens/member/index.tsx
  src/screens/member/types/index.ts
  src/services/member/index.ts
  src/services/member/types.ts
Labels: 👨🏻 규진 👨🏻, ✨ feature

#70 Feature/#69 - 비서 채팅 기능 구현
  src/assets/images/png/secretary/avartar.png
  src/constants/mutationKeys.ts
  src/screens/secretary/components/ScretaryProfile/index.style.ts
  src/screens/secretary/components/ScretaryProfile/index.tsx
  src/screens/secretary/components/SecretaryChatList/index.style.ts
  src/screens/secretary/components/SecretaryChatList/index.tsx
  src/screens/secretary/constants/mockData.ts
  src/screens/secretary/contexts/ChatContext.tsx
  src/screens/secretary/hooks/useChattingMutation.ts
  src/screens/secretary/index.style.ts
  src/screens/secretary/index.tsx
  src/screens/secretary/types/index.ts
  src/screens/secretary/utils/formatTime.ts
  src/services/secretary/index.ts
  src/services/secretary/types.ts
Labels: 👨🏻 규진 👨🏻, ✨ feature
